resumeApp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'resumeApp'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('skill/', views.SkillCreate.as_view(),name='skill'),
    path('education/', views.EducationCreate.as_view(), name='education'),
    path('work_experience/',views.Work_ExperienceCreate.as_view(), name='work_experience'),
    path('profile/', views.ProfileCreate.as_view(), name='profile'),
    path('summary/', views.ProfileDetail.as_view(), name='summary'),
]

resumegenerator/urls.py
from django.contrib import admin
# from django.urls import path
from resumeApp import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('resumeApp/', include('resumeApp.urls', namespace='resumes')),
    path('resumeApp/', include('django.contrib.auth.urls')),

    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('',views.Homepage.as_view(), name='homepage')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

resumeApp/models.py
from django.db import models
from django.contrib.auth.models import User, PermissionsMixin
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profiles' ,on_delete=models.CASCADE)
    # school = models.CharField(blank=True, null=True, max_length=100)
    image  = models.ImageField(upload_to='media/UserImages', default=None,null=True,blank=True)
    firstname = models.CharField(blank=True, null=True, max_length=100)
    lastname = models.CharField(blank=True, null=True, max_length=100)



    def __str__(self):
        return self.firstname
# class User(User,PermissionsMixin):
#     image  = models.ImageField(upload_to='media/UserImages', default=None,null=True,blank=True)
#     website = models.CharField(blank=True, null=True, max_length=100)
#     # email = models.EmailField()
#     def __str__(self):
#         return self.username

# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)
#
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()



class Skill(models.Model):
    possed_by = models.ForeignKey(User,related_name='skills', on_delete=models.CASCADE,null=True)
    experience = models.CharField(max_length=20, blank=True, null=True)
    name = models.CharField(blank=True,null=True,max_length=265)
    def __str__(self):
        return self.possed_by.username


class Work_Experience(models.Model):
    possed_by = models.ForeignKey(User, related_name='experiences', on_delete=models.CASCADE, null=True)
    name_of_org = models.CharField(max_length=50, blank=True, null=True)
    designation = models.CharField(max_length=50, blank=True, null=True)
    start_date = models.DateField()
    end_date = models.DateField()
    bio = models.TextField()

    # def __str__(self):
    #     return self.possed_by.username

class Education(models.Model):
    possed_by = models.ForeignKey(User, related_name='educations', on_delete=models.CASCADE, null=True)
    name_of_institute = models.CharField(max_length=50, blank=True, null=True)
    course = models.CharField(max_length=50, blank=True, null=True)
    start_date = models.DateField()
    end_date = models.DateField()

    # def __str__(self):
    #     return self.possed_by.username

resumeApp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth import get_user_model
from .models import Education, Profile, Skill, Work_Experience


class UserForm(UserCreationForm):
    class Meta():
        model = get_user_model()
        fields = ('username','email','password1','password2')


class EducationForm(forms.ModelForm):

    class Meta():
        model = Education
        fields = '__all__'

class ProfileForm(forms.ModelForm):

    class Meta():
        model = Profile
        fields = '__all__'






class SkillForm(forms.ModelForm):

    class Meta():
        model = Skill
        fields = '__all__'

    

class Work_ExperienceForm(forms.ModelForm):

    class Meta():
        model = Work_Experience
        fields = '__all__'

resumeApp/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Education, Profile, Skill, Work_Experience
from django.contrib.auth.models import User
# Create your views here.

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import *
from .models import *

class SignUp(CreateView):
    form_class = UserForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

class TestPage(TemplateView):
    template_name='test.html'
#
class ThanksPage(TemplateView):
    template_name='thanks.html'

class Homepage(TemplateView):
    template_name='index.html'



class ProfileCreate(CreateView,LoginRequiredMixin):
    template_name = 'profile.html'
    # form_class = ProfileForm
    success_url = reverse_lazy('resumeApp:education')
    model = Profile
    fields = ['firstname' , 'lastname' , 'image']

    def form_valid(self, form):
        form.instance.user = self.request.user

        return super(ProfileCreate, self).form_valid(form)









class EducationCreate(CreateView,LoginRequiredMixin):
    template_name = 'education.html'
    # form_class = EducationForm
    success_url = reverse_lazy('resumeApp:skill')
    model = Education
    fields = ['name_of_institute', 'course', 'start_date', 'end_date']
    def form_valid(self, form):
        form.instance.possed_by = self.request.user

        return super(EducationCreate, self).form_valid(form)

class SkillCreate(CreateView,LoginRequiredMixin):
    template_name = 'skill.html'
    # form_class = SkillForm
    model = Skill
    success_url = reverse_lazy('resumeApp:work_experience')
    fields = ['name' ,'experience']

    def form_valid(self, form):
        form.instance.possed_by = self.request.user

        return super(SkillCreate, self).form_valid(form)



class Work_ExperienceCreate(CreateView, LoginRequiredMixin):
    template_name = 'work_experience.html'
    # form_class = Work_ExperienceForm
    model = Work_Experience
    success_url = reverse_lazy('resumeApp:summary')

    fields = ['name_of_org', 'designation','bio', 'start_date', 'end_date']
    def form_valid(self, form):
        form.instance.possed_by = self.request.user

        return super(Work_ExperienceCreate, self).form_valid(form)















class ProfileDetail(ListView, LoginRequiredMixin):
    model = Profile
    template_name = 'summary.html'


class Work_ExperienceDetail(DetailView, LoginRequiredMixin):
    model = Work_Experience
    template_name = 'summary.html'

class SkillDetail(DetailView, LoginRequiredMixin):
    model = Skill
    template_name = 'summary.html'

class EducationDetail(DetailView, LoginRequiredMixin):
    model = Education
    template_name = 'summary.html'

resumeApp/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Site</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-inverse">
      <div class="container-fluid">
        <ul class='nav navbar-nav'>

          <li><a class=' navbar-brand bigbrand' href="{% url 'homepage' %}">Resume Generator</a></li>


          <li><a href="https://vit.edu.in/">About</a></li>
          <li><a href="https://www.github.com">Github</a></li>
          <li><a href="https://www.linkedin.com">LinkedIn</a></li>


        </ul>



        <ul class='nav navbar-nav navbar-right'>
          {% if user.is_authenticated %}
            <!-- <li><a href="#">Share Now</a>
            </li> -->






            <li>
                <a href="{% url 'logout' %}">Log Out</a>
            </li>

            <li>
                <a href="#">Welcome: {{user.username}}</a>
            </li>
            {% else %}
            <li><a href="{% url 'resumeApp:login' %}"><span class='glyphicon glyphicon-user'></span>Login</a></li>
            <li><a href="{% url 'resumeApp:signup' %}"><span class='glyphicon glyphicon-user'></span>Sign Up</a></li>

          {% endif %}

      </div>

    </nav>





    <div class="container">
      <div class="jumbotron">
        {% block body_block%}
        {% endblock %}

      </div>

    </div>

  </body>
</html>

resumeApp/templates/education.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container">
  <h1>EDUCATION</h1>
  <form  method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="btn btn-primary" value="NEXT">

  </form>

</div>

{% endblock %}

resumeApp/templates/index.html
{% extends "base.html" %}
{% block body_block%}
  <h1>Welcome to Resume Generator</h1>
  {% if user.is_authenticated %}
    <a href="{% url 'resumeApp:profile' %}">Create Now!</a>
    {% endif %}
{% endblock%}

resumeApp/templates/login.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container">
  <h1>Login</h1>
  <form  method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="btn btn-primary" value="LOG IN">

  </form>

</div>

{% endblock %}

resumeApp/templates/profile.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container">
  <h1>YOUR IMAGE</h1>
  <form  method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="btn btn-primary" value="NEXT">

  </form>

</div>

{% endblock %}

resumeApp/templates/signup.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container">
  <h1>Sign Up</h1>
  <form  method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="btn btn-primary" value="LOG IN">

  </form>

</div>

{% endblock %}

resumeApp/templates/skill.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container">
  <h1>SKILLS</h1>
  <form  method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="btn btn-primary" value="NEXT">

  </form>

</div>

{% endblock %}

resumeApp/templates/summary.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}






{% if user.is_authenticated %}





<p>{{user.profiles.firstname}}</p>







{% for skill in user.skills.all %}



    <p>{{skill.name}}</p>





{% endfor %}



{% for experience in user.experiences.all %}
<p>{{ experience.bio }}</p>

{% endfor %}




{% endif %}









{% endblock %}

resumeApp/templates/test.html
{% extends 'base.html'%}
{% block body_block%}
<h1>Welcome to the Resume Generator</h1>
<!-- <h2>Sign Up Now To Explore More!!!</h2> -->
{% endblock%}

resumeApp/templates/thanks.html
{% extends 'base.html'%}
{% block body_block%}
<h1>Thanks for Visiting!!!</h1>
{% endblock%}

resumeApp/templates/work_experience.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container">
  <h1>WORK EXPERIENCE</h1>
  <form  method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="btn btn-primary" value="NEXT">

  </form>

</div>

{% endblock %}